import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/Layout/NavBar";
import SideBar from "@/components/Layout/SideBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased relative h-[100vh]`}
      >
        <div className="sticky top-0 bg-theme-orange">
          <NavBar />
        </div>
        <div className="fixed w-[260px] left-0 h-[100vh] border-r overflow-clip">
          <SideBar />
        </div>
        <div className="ml-[260px] px-4 overflow-scroll">
          {children}
        </div>
      </body>
    </html>
  );
}
