
import type { Metadata } from "next";
import "./globals.css";
import LayoutWrapper from "@/components/Layout/LayoutWrapper";
import { CategoryProvider } from "@/store/CategoryContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased relative h-screen flex flex-col lg:flex-row`}>
        <CategoryProvider>
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
        </CategoryProvider>
      </body>
    </html>
  );
}